### ISSUE TITLE
preset-prettier integration broken after update of remark-preset-prettier to 2.0.0

### ISSUE THREAD

**Issue by enqueue** [mdx-js/eslint-mdx#427]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

eslint-plugin-mdx 2.0.4

### Link to runnable example

Not runnable, but easily made runnable: https://github.com/enqueue/eslint-mdx-reproducer

### Steps to reproduce

1. Set up a project with eslint-plugin-mdx and remark-preset-prettier version 2.0.0
2. Add "preset-prettier" plugin to projects `remarkrc`
3. Run `eslint .`

(Hopefully) minimal reproducible example over here: https://github.com/enqueue/eslint-mdx-reproducer

Node version is 18.9

### Expected behavior

MDX and MD files are linted according to rules.

### Actual behavior

Error message `0:0  error  Parsing error: Cannot find module 'preset-prettier'`.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm v8

### OS

Linux

### Workaround

My current workaround is to pin the dependency of remark-preset-prettier to 1.0.2

**Comment by JounQin** [comment]
Thanks for reproduction, I'll check soon.

**Comment by JounQin** [comment]
@enqueue Please use `remark-preset-prettier@2.0.1` before next version of `eslint-mdx`. They fix this issue if different ways.

**Comment by enqueue** [comment]
@JounQin thanks for the super-fast fix. I wasn't sure in which project this bug report belonged.

**Comment by JounQin** [comment]
I maintain both `eslint-mdx` and `remark-preset-prettier` at the same time.

> I wasn't sure in which project this bug report belonged.

It is indeed an issue at `eslint-mdx`'s side, but there could be a workaround from `remark-preset-prettier`.
